### ISSUE TITLE
mmsplayer源码

### ISSUE THREAD

**Issue by ViewUse** [Zephor5/MmsRadio#1]
看你名字应该是中国人吧！
我能请你帮一个忙吗， 在方便的情况下能把jni 包的源码一起上传吗？？
谢谢.....

**Comment by Zephor5** [comment]
忙着毕业，没上来转转，回晚了
我也没有jni的源码的，lib是在csdn上下载的。以为没啥人看，就没做说明。
我想这个/biophysics/RadioPlayer 项目会对你有帮助
